# Generated by Django 5.0.1 on 2024-02-12 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("BookListAPI", "0003_category_menuitem_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
